global-variables:
  environment: &default_environment
    REGISTRY:
      from_secret: artifactory-host-01
    REGISTRY_HELM_PROJECT:  
      from_secret: artifactory-helm-project-01
    USERNAME:
      from_secret: artifactory-user-01
    PASSWORD:
      from_secret: artifactory-password-01


kind: pipeline
type: docker
name: default
platform:
  os: linux
  arch: amd64

steps:  
  - name: Fix permissions on build-cache directory
    image: alpine
    volumes:  
    - name: cache
      path: /drone/cache
    commands:
    - chown -R 1001:0 /drone/cache && chmod -R g+=wrx /drone/cache

  - name: Lint helm chart
    image: alpine/helm:3.15.2
    environment:
      <<: *default_environment
    commands:
    - echo "Linting helm chart"
    - cd ./charts/powerdns-admin && helm dependency update && helm lint

## only on release
  - name: Package and deploy chart
    image: alpine/helm:3.15.2
    environment:
      <<: *default_environment
    commands:
    - helm registry login $${REGISTRY} -u $${USERNAME} -p $${PASSWORD}
    - cd ./charts/powerdns-admin
    - helm package .
    - helm push *.tgz oci://$${REGISTRY}/$${REGISTRY_HELM_PROJECT}
    - helm registry logout $${REGISTRY}
    when:
      event:
      - tag
      ref:
      - refs/tags/v*

volumes:
- name: cache
  temp: {}

trigger:
  event:
  - tag
  - push
  - pull_request
