apiVersion: v1
kind: Secret
metadata:
  name: {{ include "powerdns-admin.fullname" . }}
  labels:
    {{- include "powerdns-admin.labels" . | nindent 4 }}
data:
  session-secret: {{ .Values.sessionKey | default (randAlphaNum 32) | b64enc | quote }}